<?php
	require_once( $_SERVER['DOCUMENT_ROOT']."/libs/verify_session.php" );
	require_once( $_SERVER['DOCUMENT_ROOT']."/translations/admin_panel_cu_home.php" );
	

	//db
	include_once( $_SERVER['DOCUMENT_ROOT']."/libs/db_common.php" );
	
	$ErrMsg = "";
	$OkMsg  = "";
	
	/*
	ajax params: 
		"ajaxRequest" : "loadData", (string)
		"keyword"     : keyword,    (string)
		"supplier"    : supplier,   (boolean)
		"consumer"    : consumer,   (boolean)
		"advertiser"  : advertiser, (boolean)
		"priside"     : priside,    (boolean) 
		"company"     : company,    (boolean)
		"builder"     : builder,    (boolean)
		"tenant"      : tenant,     (boolean)
		"ngo"         : ngo,        (boolean)
		"authority"   : authority,  (boolean)
		"records"     : records,    (integer)
		"page"        : page,       (integer)
		"checksum"    : checksum    (checksum generated by the server)
	*/
	if("loadCustomers" == $ajaxRequest){
		// sanity checks on variables
		if(!VerifyCheckSum($records.$page,$checksum)){
			$ErrMsg = "CheckSum Error @ ".__LINE__;
			header("Status: 400 " . $ErrMsg );
			exit(0);
		}
		db_connect();
		
		//filter variables
		$keyword     = isset($keyword)         ? mysql_real_escape_string($keyword)      : "";
		$supplier    = ($supplier   == "true") ? "A.Type=3"           : ""; //Premium
		$consumer    = ($consumer   == "true") ? "A.Type=1"           : ""; //Regular
		$advertiser  = ($advertiser == "true") ? "A.Type=2"           : ""; //Advertiser
		$priside     = ($priside    == "true") ? "A.Type=4"           : ""; //Priside
		$company     = ($company    == "true") ? "B.Classification=2" : ""; //company
		$builder     = ($builder    == "true") ? "B.Classification=3" : ""; //general contractor
		$tenant      = ($tenant     == "true") ? "B.Classification=4" : ""; //strata
		$ngo         = ($ngo        == "true") ? "B.Classification=5" : ""; //non-profit
        $authority   = ($authority  == "true") ? "B.Classification=6" : ""; //government
		
		//paging variables
		$records     = isset($records) ? $records : 20;
		$page        = isset($page)    ? $page    : 1;
		$offset      = ($page - 1) * $records;
		
		$sql_count   = "
						SELECT
							COUNT(DISTINCT A.Id)
						FROM
						  Accounts A INNER JOIN User U ON A.PrimaryUser_Id = U.Id
						  LEFT JOIN Business B ON B.Id = A.Business_Id
						  LEFT JOIN BusinessServiceCategoryGroup BSCG ON B.Id = BSCG.Business_Id
						  LEFT JOIN BusinessServiceCategory BSC ON BSC.Id = BSCG.BusinessServiceCategory_Id
						  LEFT JOIN BusinessServiceLanKommunerGroup BSLKG ON B.Id = BSLKG.Business_Id
						  LEFT JOIN Sweden_LanKommuner SLK ON SLK.Id = BSLKG.Sweden_LanKommuner_Id
						WHERE
						  ((A.IsDeleted = 0 OR A.IsDeleted IS NULL) AND A.Id NOT IN (SELECT Id FROM Accounts WHERE Type = 'Priside'))
					   ";
		$sql_count  .= appendConditions($keyword,$supplier,$consumer,$advertiser,$priside,$company,$builder,$tenant,$ngo,$authority);
		$result      = mysql_query($sql_count);
		$count       = mysql_fetch_row($result);
		$count       = $count[0];
		mysql_free_result($result);
		$total_pages = ceil((int)$count / $records);
		
		$sql = "
				SELECT
				  A.Id AS Account_Id,
				  U.Id AS User_Id,
				  CASE WHEN LENGTH(B.Name) = 0 OR B.Name IS NULL THEN CONCAT_WS(' ',U.FirstName,U.LastName) ELSE B.Name END AS Name,
				  B.OrgNumber,
				  CONCAT_WS('<br>',B.City,GROUP_CONCAT(DISTINCT SLK.name ORDER BY SLK.name ASC SEPARATOR ',<br>')) AS Location,
				  GROUP_CONCAT(DISTINCT BSC.Category ORDER BY BSC.Category ASC SEPARATOR ',<br>') AS Category,
				  A.Type,
				  MAX(U.LastLogin) AS LastLogin,
				  A.Active,
				  CASE WHEN U.IsPrisideAdmin = 1 AND A.Type = 'Priside' THEN 'Yes' ELSE 'No' END AS IsPrisideAdmin
				FROM
				  Accounts A INNER JOIN User U ON A.PrimaryUser_Id = U.Id
				  LEFT JOIN Business B ON B.Id = A.Business_Id
				  LEFT JOIN BusinessServiceCategoryGroup BSCG ON B.Id = BSCG.Business_Id
				  LEFT JOIN BusinessServiceCategory BSC ON BSC.Id = BSCG.BusinessServiceCategory_Id
				  LEFT JOIN BusinessServiceLanKommunerGroup BSLKG ON B.Id = BSLKG.Business_Id
				  LEFT JOIN Sweden_LanKommuner SLK ON SLK.Id = BSLKG.Sweden_LanKommuner_Id
				WHERE
				  ((A.IsDeleted = 0 OR A.IsDeleted IS NULL) AND A.Id NOT IN (SELECT Id FROM Accounts WHERE Type = 'Priside'))
			   ";
		$sql.= appendConditions($keyword,$supplier,$consumer,$advertiser,$priside,$company,$builder,$tenant,$ngo,$authority);
		$sql.= "		
				GROUP BY
				  A.Id  
				ORDER BY
				  B.Name ASC
				LIMIT 
				  $offset,$records
			   ";
		$result = mysql_query($sql);
		if(0 != mysql_errno()){
			$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
			header("Status: 400 " . $ErrMsg );
			exit(0);
		}
		
		ob_start();
		$rowNum = 0;
		while($row = mysql_fetch_assoc($result)){
			$rowNum+=1;
			$rowType = $rowNum % 2 == 0 ? "even" : "odd";
			include("inc_admin_panel_cu_home_rowSnippet.html");
		}
		mysql_free_result($result);
		
		$result_data_html = ob_get_contents();
		ob_end_clean();
		
		if(0 != $rowNum){
			print $result_data_html;
		}
		else{
			print "<div style=\"text-align:center;padding-top:5px;color:#E66313;font-weight:bold;\">{$trans["cu_home_no_records_found"]}</div>";
		}
		exit(0);
	}	
	
	/*
		description :
			appends keyword and other search filters to the query;
		params :
			$keyword
			$supplier
			$consumer
			$advertiser
			$priside
			$company
			$builder
			$tenant
			$ngo
			$authority
		returns :
			appended filters
	*/
	function appendConditions($keyword,$supplier,$consumer,$advertiser,$priside,$company,$builder,$tenant,$ngo,$authority){
		$keyword = utf8_decode(trim($keyword)); //make sure we decode it
		$sql = "";
		if(!empty($keyword)){
			/*SLK.name = location*/
			/*BSC.Category = category*/
			
			$sql.= "
					AND
					A.Id         LIKE '%$keyword%' OR
					B.Name       LIKE '%$keyword%' OR
					B.OrgNumber  LIKE '%$keyword%' OR 
					B.City       LIKE '%$keyword%' OR
					SLK.name     LIKE '%$keyword%' OR 
					BSC.Category LIKE '%$keyword%'
				  ";
		}
		
		if(!empty($supplier)){
			if(!empty($keyword)){
				$sql.= " OR $supplier";
			}
			else{
				$sql.= " AND $supplier";
			}
		}
		
		if(!empty($consumer)){
			if(!empty($keyword) ||!empty($supplier)){
				$sql.= " OR $consumer";
			}
			else{
				$sql.= " AND $consumer";
			}
		}
		
		if(!empty($advertiser)){
			if(!empty($keyword) || !empty($supplier) || !empty($consumer)){
				$sql.= " OR $advertiser";
			}
			else{
				$sql.= " AND $advertiser";
			}
		}
		
		
		if(!empty($priside)){
			if(!empty($keyword) || !empty($supplier) || !empty($consumer) || !empty($advertiser)){
				$sql.= " OR $priside";
			}
			else{
				$sql.= " AND $priside";
			}
		}
		
		if(!empty($company)){
			if(!empty($keyword) || !empty($supplier) || !empty($consumer) || !empty($advertiser) || !empty($priside)){
				$sql.= " OR $company";
			}
			else{
				$sql.= " AND $company";
			}
		}
		
		if(!empty($builder)){
			if(!empty($keyword) || !empty($supplier) || !empty($consumer) || !empty($advertiser) || !empty($priside) || !empty($company)){
				$sql.= " OR $builder";
			}
			else{
				$sql.= " AND $builder";
			}
		}
		
		if(!empty($tenant)){
			if(!empty($keyword) || !empty($supplier) || !empty($consumer) || !empty($advertiser) || !empty($priside) || !empty($company) || !empty($builder)){
				$sql.= " OR $tenant";
			}
			else{
				$sql.= " AND $tenant";
			}
		}
		
		if(!empty($ngo)){
			if(!empty($keyword) || !empty($supplier) || !empty($consumer) || !empty($advertiser) || !empty($priside) || !empty($company) || !empty($builder) || !empty($tenant)){
				$sql.= " OR $ngo";
			}
			else{
				$sql.= " AND $ngo";
			}
		}
		
		if(!empty($authority)){
			if(!empty($keyword) || !empty($supplier) || !empty($consumer) || !empty($advertiser) || !empty($priside) || !empty($company) || !empty($builder) || !empty($tenant) || !empty($ngo)){
				$sql.= " OR $authority";
			}
			else{
				$sql.= " AND $authority";
			}
		}
		return $sql;
	}
	
	//how to create checksum
	//$checksum = CheckSum($page.$records);
	//verify checksum
	//VerifyCheckSum($olddata,$oldchecksum)
	include("inc_admin_panel_cu_home.html");
	return;
?>
