<?php
	require_once( $_SERVER['DOCUMENT_ROOT']."/libs/verify_session.php" );
	require_once( $_SERVER['DOCUMENT_ROOT']."/translations/customer_info_general.php" );
	
	//db
	include_once( $_SERVER['DOCUMENT_ROOT']."/libs/db_common.php" );
	
	$ErrMsg = "";
	$OkMsg  = "";
	
	/*
		ajax params: 
			"ajaxRequest"		 : ajaxRequest        (string) 
			"accountId"          : accountId          (integer)
			"customerId"  		 : customerId         (integer)
			"businessId"  		 : businessId         (integer)
			"accountType         : accountType        (string)
			"accountManagerName" : accountManagerName (string)
			"note"               : note               (string)
			"checksum"           : checksum           (checksum generated by the server)
	*/
	
	// sanity checks on variables
	if(!VerifyCheckSum($customerId,$checksum)){
		$ErrMsg = "CheckSum Error @ ".__LINE__;
		header("Status: 400 " . $ErrMsg );
		exit(0);
	}
	
	//db
	include_once( $_SERVER['DOCUMENT_ROOT']."/libs/db_common.php" );
	db_connect();
	if("changeAccountType" == $ajaxRequest){
		$accountType = utf8_decode(mysql_real_escape_string($accountType));
		$sql         = "UPDATE Accounts SET Type = '$accountType' WHERE Id = $accountId";
		$result      = mysql_query($sql);
		if(0 != mysql_errno()){
			$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
			header("Status: 400 " . $ErrMsg );
			exit(0);
		}
		print $trans["cust_nfo_gen_account_type_change_success"];
		exit(0);
	}
	else if("updateBusiness" == $ajaxRequest){
		$accountManagerName = utf8_decode(mysql_real_escape_string($accountManagerName));
		$note               = utf8_decode(mysql_real_escape_string($note));
		$sql                = "UPDATE Business SET AccountManagerName = '$accountManagerName' , Note = '$note' WHERE Id = $businessId LIMIT 1";
		$result             = mysql_query($sql);
		if(0 != mysql_errno()){
			$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
			header("Status: 400 " . $ErrMsg );
			exit(0);
		}
		print $trans["cust_nfo_gen_business_update_success"];
		exit(0);
	}
	else if("deleteAccount" == $ajaxRequest){
		$sql         = "UPDATE Accounts SET IsDeleted = 1 , DeletedDate = NOW() WHERE Id = $accountId LIMIT 1";
		$result      = mysql_query($sql);
		if(0 != mysql_errno()){
			$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
			header("Status: 400 " . $ErrMsg );
			exit(0);
		}
		print $trans["cust_nfo_gen_business_deleted_success"];
		exit(0);
	}
	else if("enableAccount" == $ajaxRequest){
		$sql         = "UPDATE Accounts SET Active = 1 WHERE Id = $accountId LIMIT 1";
		$result      = mysql_query($sql);
		if(0 != mysql_errno()){
			$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
			header("Status: 400 " . $ErrMsg );
			exit(0);
		}
		print $trans["cust_nfo_gen_business_enabled_success"];
		exit(0);
	}
	else if("disableAccount" == $ajaxRequest){
		$sql         = "UPDATE Accounts SET Active = 0 WHERE Business_Id = $businessId LIMIT 1";
		$result      = mysql_query($sql);
		if(0 != mysql_errno()){
			$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
			header("Status: 400 " . $ErrMsg );
			exit(0);
		}
		print $trans["cust_nfo_gen_business_disabled_success"];
		exit(0);
	}
	else if("loadData" == $ajaxRequest){
		/*	LABEL NAME							 FIELD NAME
			-------------------------------------------------------------------------------------
			Org.nr                             = B.OrgNumber
			Customer                           = U.Id
			Organization                       = B.Classification
			Industry                           = BSC.Category (one or more)

			Answer Inquiries /Ads              = ?
			Completed Assignments / Active Ads = ?
			Status                             = A.Active

			Registered                         = B.ActivatedDate
			Last Seen                          = U.LastLogin
			Last Invoiced                      = PresideBilling.Date *(where Paid = 1)
			Next Billing                       = PresideBilling.NextBillDate *(where Paid = 1)
			Sales / Account Manager            = B.AccountManagerName
			Notes                              = B.Notes
		*/
		
		$sql = "
				SELECT
				  B.Id AS Business_Id,
				  B.Name,
				  B.OrgNumber,
				  U.Id,
				  B.Classification,
				  CONCAT_WS('<br>&nbsp;&nbsp;&nbsp;','',GROUP_CONCAT(DISTINCT BSC.Category ORDER BY BSC.Category ASC SEPARATOR '<br>&nbsp;&nbsp;&nbsp;')) AS Category,
				  A.Active,
				  B.ActivatedDate,
				  U.LastLogin,
				  PSB.Date,
				  PSB.NextBillDate,
				  B.AccountManagerName,
				  B.Note,
				  A.Type
				FROM
				  Accounts A INNER JOIN User U ON A.Id = U.Account_Id
				  LEFT JOIN Business B ON B.Id = A.Business_Id
				  LEFT JOIN BusinessServiceCategoryGroup BSCG ON B.Id = BSCG.Business_Id
				  LEFT JOIN BusinessServiceCategory BSC ON BSC.Id = BSCG.BusinessServiceCategory_Id
				  LEFT JOIN BusinessServiceLanKommunerGroup BSLKG ON B.Id = BSLKG.Business_Id
				  LEFT JOIN PresideBilling PSB ON A.Id = PSB.Account_Id
				WHERE
					U.Id = $customerId
				GROUP BY
					U.Id
				LIMIT 1
			   ";
		$result = mysql_query($sql);
		if(0 != mysql_errno()){
			$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
			header("Status: 400 " . $ErrMsg );
			exit(0);
		}
		$row = mysql_fetch_assoc($result);
		mysql_free_result($result);
	}
	include( "inc_customer_info_general.html" );
	return;

?>