<?php
	require_once( $_SERVER['DOCUMENT_ROOT']."/libs/verify_session.php" );
	require_once( $_SERVER['DOCUMENT_ROOT']."/translations/customer_info_cinfo.php" );
	
	$ErrMsg = "";
	$OkMsg  = "";
	
	/*
		ajax params: 
			"ajaxRequest"		 : ajaxRequest        (string)
			"accountId"          : accountId          (number)
			"customerId"  		 : customerId         (number)
			"businessId"  		 : businessId         (number)
			"classification"     : classification     (string)
			"company"            : company            (string) 
			"firstName"          : firstName          (string) 
			"lastName"           : lastName           (string) 
			"personNumber"       : personNumber       (string) 
			"phone"              : phone              (string) 
			"address"            : address            (string) 
			"email"              : email              (string)  
			"altPhone"           : altPhone           (string) 
			"postal"             : postal             (string) 
			"city"               : city               (string) 
			"serviceId"          : serviceId          (string) 
			"municipalityId"     : municipalityId     (string) 
			"checksum"           : checksum           (checksum generated by the server)
	*/
	
	// sanity checks on variables
	if(!VerifyCheckSum($customerId,$checksum)){
		$ErrMsg = "CheckSum Error @ ".__LINE__;
		header("Status: 400 " . $ErrMsg );
		exit(0);
	}
	
	//db
	include_once( $_SERVER['DOCUMENT_ROOT']."/libs/db_common.php" );
	db_connect();
	
	if("updateBusiness" == $ajaxRequest){
		$company             = utf8_decode(mysql_real_escape_string($company));
		$classification      = utf8_decode(mysql_real_escape_string($classification));
		$firstName           = utf8_decode(mysql_real_escape_string($firstName));
		$lastName            = utf8_decode(mysql_real_escape_string($lastName));
		$orgNumber           = utf8_decode(mysql_real_escape_string($orgNumber));
		$personNumber        = utf8_decode(mysql_real_escape_string($personNumber)); 
		$phone               = utf8_decode(mysql_real_escape_string($phone)); 
		$address             = utf8_decode(mysql_real_escape_string($address));
		$email               = utf8_decode(mysql_real_escape_string($email));
		$altPhone            = utf8_decode(mysql_real_escape_string($altPhone));
		$postal		         = utf8_decode(mysql_real_escape_string($postal));
		$city                = utf8_decode(mysql_real_escape_string($city));
		$serviceId           = utf8_decode(mysql_real_escape_string($serviceId));
		$municipalityId      = utf8_decode(mysql_real_escape_string($municipalityId));
		
		//start transaction
		mysql_query("BEGIN");
		
		//flag if business is new
		$businessIsNew = $businessId == 0 ? true : false;
		
		//lets dynamically build the query for the business table
		$business_fields = "";
		$business_values = "";
		foreach($_POST as $key => $value){
			if("ajaxRequest" != $key && "accountId" != $key && "customerId" != $key && "businessId" != $key && "serviceId" != $key && "municipalityId" != $key && "contract" != $key && "recording" != $key && "checksum" != $key){
				if(!empty($value)){
					if($businessIsNew){
						//insert
						$business_fields.= ucwords($key).",";
						$business_values.="'".utf8_decode(mysql_real_escape_string($value))."',";
					}
				}
				//fields can be set to blank
				if(!$businessIsNew){
					//update
					$business_values.= ucwords($key)." = '".utf8_decode(mysql_real_escape_string($value))."',";
				}
			}
		}
		$business_fields = rtrim($business_fields,",");
		$business_values = rtrim($business_values,",");
		
		if(!$businessIsNew){
			$sql = "UPDATE Business SET $business_values WHERE Id = $businessId LIMIT 1";
		}
		else{
			$sql = "INSERT INTO Business ($business_fields,CreateDate) VALUES ($business_values,NOW())";
		}
		
		$result = mysql_query($sql);
		if(0 != mysql_errno()){
			mysql_query("ROLLBACK");
			$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
			header("Status: 400 " . $ErrMsg );
			exit(0);
		}
		$businessId = ($businessIsNew) ? mysql_insert_id() : $businessId;
		
		//update account when business is new
		if($businessIsNew){
			$sql = "UPDATE Accounts SET Business_Id = $businessId WHERE Id = $accountId LIMIT 1";
			$result = mysql_query($sql);
			if(0 != mysql_errno()){
				mysql_query("ROLLBACK");
				$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
				header("Status: 400 " . $ErrMsg );
				exit(0);
			}
		}
		
		//delete the unselected service
		if(!empty($serviceId)){
			$sql_delete_service = "DELETE FROM BusinessServiceCategoryGroup WHERE BusinessServiceCategory_Id NOT IN ($serviceId) AND Business_Id = $businessId";
			$result = mysql_query($sql_delete_service);
			if(0 != mysql_errno()){
				mysql_query("ROLLBACK");
				$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
				header("Status: 400 " . $ErrMsg );
				exit(0);
			}
		}
		
		//delete the unselected municipality
		if(!empty($municipalityId)){
			$sql_delete_municipality = "DELETE FROM BusinessServiceLanKommunerGroup WHERE Sweden_LanKommuner_Id NOT IN ($municipalityId) AND Business_Id = $businessId";
			$result = mysql_query($sql_delete_municipality);
			if(0 != mysql_errno()){
				$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
				header("Status: 400 " . $ErrMsg );
				mysql_query("ROLLBACK");
				exit(0);
			}
		}
		
		//insert industries
		//get the old values
		$sql          = "SELECT GROUP_CONCAT(BusinessServiceCategory_Id) AS Services FROM BusinessServiceCategoryGroup WHERE Business_Id = $businessId LIMIT 1";
		$result       = mysql_query($sql);
		$services_old = mysql_fetch_assoc($result);
		mysql_free_result($result);
		//get only the new values
		$services     = array_diff(explode(",",$serviceId),explode(",",$services_old["Services"]));
		
		//execute query when there are new values
		if(count($services) > 0){
			$sql_service = "INSERT INTO BusinessServiceCategoryGroup (Business_Id,BusinessServiceCategory_Id) VALUES";
			foreach($services as $businessServiceCategory_Id){
				$sql_service.="($businessId,$businessServiceCategory_Id),";
			}	
			$sql_service = rtrim($sql_service,",");
			
			$result = mysql_query($sql_service);
			if(0 != mysql_errno()){
				mysql_query("ROLLBACK");
				$ErrMsg = mysql_error()." @line:".__LINE__;
				header("Status: 400 " .$ErrMsg);
				exit(0);
			}
		}
		
		//insert municipalities
		//get the old values
		$sql                = "SELECT GROUP_CONCAT(Sweden_LanKommuner_Id) AS Municipalities FROM BusinessServiceLanKommunerGroup WHERE Business_Id = $businessId LIMIT 1";
		$result             = mysql_query($sql);
		$municipalities_old = mysql_fetch_assoc($result);
		mysql_free_result($result);
		//get only the new values
		$municipalities     = array_diff(explode(",",$municipalityId),explode(",",$municipalities_old["Municipalities"]));
		
		//execute query when there are new values
		if(count($municipalities) > 0){
			$sql_municipality   = "INSERT INTO BusinessServiceLanKommunerGroup (Business_Id,Sweden_LanKommuner_Id) VALUES";
			foreach($municipalities as $sweden_LanKommuner_Id){
				$sql_municipality.="($businessId,$sweden_LanKommuner_Id),";
			}	
			$sql_municipality = rtrim($sql_municipality,",");
			
			$result = mysql_query($sql_municipality);
			if(0 != mysql_errno()){
				mysql_query("ROLLBACK");
				$ErrMsg = mysql_error()." @line:".__LINE__;
				header("Status: 400 " .$ErrMsg);
				exit(0);
			}
		}
		
		//transaction was successfull
		mysql_query("COMMIT");
		print $trans["cust_nfo_cinfo_update_success"];
		exit(0);
	}
	else if("loadData" == $ajaxRequest){
		$sql = "
				SELECT
					A.Id AS AccountId,
					CAST(A.Type AS UNSIGNED) AS Type,
					CASE WHEN B.Id IS NULL THEN 0 ELSE B.Id END AS Id,
					CASE WHEN LENGTH(B.Classification) = 0 OR B.Classification IS NULL THEN '{$trans["cust_nfo_organization"]}' ELSE B.Classification END AS Classification_Name,
					CASE WHEN CAST(B.Classification AS UNSIGNED) IS NULL THEN '' ELSE CAST(B.Classification AS UNSIGNED) END AS Classification_Value,
					B.OrgNumber,
					B.Name Company,
					CASE WHEN B.FirstName IS NULL THEN U.FirstName ELSE B.FirstName END AS FirstName,
					CASE WHEN B.LastName IS NULL THEN U.LastName ELSE B.LastName END AS LastName,
					B.OrgNumber,
					B.PersonNumber,
					CASE WHEN B.Phone IS NULL THEN U.Phone ELSE B.Phone END AS Phone,
					B.Address,
					B.AccountManagerName,
					CASE WHEN B.Email IS NULL THEN U.Email ELSE B.Email END AS Email,
					CASE WHEN B.AltPhone IS NULL THEN U.AltPhone ELSE B.AltPhone END AS AltPhone,
					B.Postal,
					B.City,
					GROUP_CONCAT(DISTINCT BSCG.BusinessServiceCategory_Id ORDER BY BSCG.BusinessServiceCategory_Id ASC SEPARATOR ',') AS Service,
					GROUP_CONCAT(DISTINCT BSLG.Sweden_LanKommuner_Id ORDER BY BSLG.Sweden_LanKommuner_Id ASC SEPARATOR ',') AS Municipality
				FROM
					Accounts A INNER JOIN User U ON A.Id = U.Account_Id
					LEFT JOIN Business B ON B.Id = A.Business_Id
					LEFT JOIN BusinessServiceCategoryGroup BSCG ON B.Id = BSCG.Business_Id
					LEFT JOIN BusinessServiceLanKommunerGroup BSLG ON B.Id = BSLG.Business_Id
				WHERE 
					U.Id = $customerId
				GROUP BY 
					A.Id
				LIMIT 1
			   ";
		$result = mysql_query($sql);
		if(0 != mysql_errno()){
			$ErrMsg = "Query Error @ ".__LINE__." ". mysql_error();
			header("Status: 400 " . $ErrMsg );
			exit(0);
		}
		$row = mysql_fetch_assoc($result);
		mysql_free_result($result);
	}
	
	function toCheckBoxes($arr,$first = true){ 
		if($first){
			$html = "<ul style=\"margin-top:0px;margin-left:-20px;\">\n";
		}
		foreach($arr as $v){
			$html .= "<li>\n";
			$html .= "<input class=\"priside-checkbox\" type=\"checkbox\" id=\"servicesCustomerInfoCinfo_{$v["Id"]}\" value=\"{$v["Id"]}\"/>\n";
			$html .= "<label for=\"servicesCustomerInfoCinfo_{$v["Id"]}\"></label>\n";
			$html .= "{$v["Category"]}\n";
			if( array_key_exists('children',$v)){
				$html .= toCheckBoxes($v['children']);     
			}
			$html .= "</li>\n";
		}   
		$html .= "</ul>\n";   
		return $html; 
	}
	
	function GetServices(){
		$refs   = array();
		$list   = array();
		$sql    = "SELECT Id, Parent_Id, Category FROM BusinessServiceCategory ORDER BY Category";
		$result = mysql_query($sql);
		while($row = mysql_fetch_assoc($result)){
			$thisref = &$refs[ $row['Id'] ];
			$thisref['Id'] = $row['Id'];
			$thisref['Parent_Id'] = $row['Parent_Id'];
			$thisref['Category'] = $row['Category'];
			if ($row['Parent_Id'] == 0) 
				$list[] = &$thisref;
			else
				$refs[$row['Parent_Id']]['children'][] = &$thisref;
		}
		return(toCheckBoxes($list,false));
	}


	function GetMunicipality(){
		$sql =     "SELECT Id,Name FROM Sweden_LanKommuner S WHERE Parent_Id <> 0 ORDER BY Name ASC";
		$result    = mysql_query($sql);
		$list_html = "";
		$rows      = 0;
		$cols      = 0;
		$total     =  mysql_num_rows($result);
		while($row = mysql_fetch_assoc($result)){
			if($cols == 0){
				$list_html .= "<div style=\"position:relative;float:left;width:105px\">\n";
			}
			
			$list_html .= "\t<div style=\"position:relative;float:left;width:110px\">\n";
			$list_html .= "\t\t<input class=\"priside-checkbox\" type=\"checkbox\" id=\"municipalityCustomerInfoCinfo_{$row["Id"]}\" value=\"{$row["Id"]}\"/>\n";
			$list_html .= "\t\t<label for=\"municipalityCustomerInfoCinfo_{$row["Id"]}\"></label>\n";
			$list_html .= "{$row["Name"]}\n";
			$list_html .= "\t</div>\n";
			
			$rows++;
			$cols++;
			
			if($cols == floor($total / 2)){
				$list_html .= "</div>\n";
				$cols = 0;
			}
			if($rows == $total ){
				$list_html .= "</div>\n";
			}
		}
		mysql_free_result($result);
		return $list_html;
	}
	
	function GetClassication(){
		//get all the enum values of table Business and column Classification
		$sql       = "SELECT COLUMN_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Business' AND COLUMN_NAME = 'Classification'";
		$result    = mysql_query($sql);
		$list_html = "";
		while($row = mysql_fetch_assoc($result)){
			//parse the values
			preg_match('/enum\((.*)\)$/', $row["COLUMN_TYPE"], $matches);
			//store it in an array
			$enums = explode(',', $matches[1]);
			//use index so that even if the string has change, we will still have the correct value
			foreach($enums as $index => $enum){
				//display only valid enums (length > 0)
				$enum = ucwords(str_replace("'","",$enum));
				if($enum != ""){
					$list_html .= "<li id=\"classification_".$enum."\" value=\"".($index + 1)."\" onclick=\"displaySelectedItem('div_org_itemsCustomerInfoCinfo', 'spn_organizationCustomerInfoCinfo', '".$enum."');setSelectedClassification('".($index + 1)."');\">".$enum."</li>\n";
				}
			}
		}
		mysql_free_result( $result );
		return $list_html;
	}
	
	include( "inc_customer_info_cinfo.html" );
	return;

?>